# Generated by Django 6.0.5 on 2026-07-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_add_phone_to_parent_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='egn',
            field=models.CharField(blank=True, max_length=10, verbose_name='ЕГН'),
        ),
    ]
