# Generated by Django 6.0.5 on 2026-07-24 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_add_egn_to_student_profile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="studentprofile",
            options={
                "ordering": ["school_class", "user__first_name", "user__last_name"],
                "verbose_name": "Ученик",
                "verbose_name_plural": "Ученици",
            },
        ),
    ]
