# Generated by Django 6.0.5 on 2026-06-02 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("school", "0002_timetable"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Заглавие")),
                ("file", models.FileField(upload_to="materials/", verbose_name="Файл")),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Качен на"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="school.class",
                        verbose_name="Клас",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="school.subject",
                        verbose_name="Предмет",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        limit_choices_to={"role": "teacher"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Учител",
                    ),
                ),
            ],
            options={
                "verbose_name": "Учебен материал",
                "verbose_name_plural": "Учебни материали",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
