# Generated by Django 6.0.5 on 2026-06-02 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Timetable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Понеделник"),
                            (2, "Вторник"),
                            (3, "Сряда"),
                            (4, "Четвъртък"),
                            (5, "Петък"),
                        ],
                        verbose_name="Ден",
                    ),
                ),
                (
                    "hour_number",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "1-ви час"),
                            (2, "2-ви час"),
                            (3, "3-ви час"),
                            (4, "4-ви час"),
                            (5, "5-ви час"),
                            (6, "6-ви час"),
                            (7, "7-ви час"),
                            (8, "8-ви час"),
                        ],
                        verbose_name="Час",
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_entries",
                        to="school.teacherclasssubject",
                        verbose_name="Назначение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Разписание",
                "verbose_name_plural": "Разписания",
                "ordering": ["day_of_week", "hour_number"],
                "unique_together": {("assignment", "day_of_week", "hour_number")},
            },
        ),
    ]
