# Generated by Django 6.0.5 on 2026-07-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0003_delete_timetable"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активен"),
        ),
        migrations.AddField(
            model_name="subject",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активен"),
        ),
        migrations.AddField(
            model_name="subject",
            name="required_room_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("standard", "Стандартна класна стая"),
                    ("computer", "Компютърен кабинет"),
                    ("gym", "Физкултурен салон"),
                    ("lab", "Лаборатория"),
                ],
                help_text="Ако е зададен, часовете по предмета се провеждат само в зала от този тип.",
                max_length=20,
                verbose_name="Подходящ тип зала",
            ),
        ),
    ]
