# Generated by Django 6.0.5 on 2026-07-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0004_class_is_active_subject_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="is_foreign_language",
            field=models.BooleanField(default=False, verbose_name="Чужд език"),
        ),
    ]
