# Generated by Django 6.0.5 on 2026-06-02 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("school", "0002_timetable"),
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Absence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата")),
                (
                    "absence_type",
                    models.CharField(
                        choices=[("unexcused", "Неизвинено"), ("excused", "Извинено")],
                        default="unexcused",
                        max_length=10,
                        verbose_name="Вид",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="absences",
                        to="students.studentprofile",
                        verbose_name="Ученик",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="absences",
                        to="school.subject",
                        verbose_name="Предмет",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        limit_choices_to={"role": "teacher"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="given_absences",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Учител",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отсъствие",
                "verbose_name_plural": "Отсъствия",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.PositiveSmallIntegerField(
                        choices=[(2, "2"), (3, "3"), (4, "4"), (5, "5"), (6, "6")],
                        verbose_name="Оценка",
                    ),
                ),
                (
                    "grade_type",
                    models.CharField(
                        choices=[
                            ("oral", "Устно изпитване"),
                            ("written", "Контролно"),
                            ("current", "Текуща"),
                        ],
                        default="current",
                        max_length=10,
                        verbose_name="Вид",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата")),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Забележка"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        to="students.studentprofile",
                        verbose_name="Ученик",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        to="school.subject",
                        verbose_name="Предмет",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        limit_choices_to={"role": "teacher"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="given_grades",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Учител",
                    ),
                ),
            ],
            options={
                "verbose_name": "Оценка",
                "verbose_name_plural": "Оценки",
                "ordering": ["-date"],
            },
        ),
    ]
