# Generated by Django 6.0.5 on 2026-07-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade_type',
            field=models.CharField(choices=[('oral', 'Устно изпитване'), ('written', 'Контролно'), ('current', 'Текуща'), ('term1', 'Срочна – 1 срок'), ('term2', 'Срочна – 2 срок'), ('annual', 'Годишна')], default='current', max_length=10, verbose_name='Вид'),
        ),
    ]
