# Generated by Django 6.0.5 on 2026-07-29 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("school", "0004_class_is_active_subject_is_active_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Номер / наименование"
                    ),
                ),
                (
                    "capacity",
                    models.PositiveSmallIntegerField(
                        default=26, verbose_name="Капацитет"
                    ),
                ),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("standard", "Стандартна класна стая"),
                            ("computer", "Компютърен кабинет"),
                            ("gym", "Физкултурен салон"),
                            ("lab", "Лаборатория"),
                        ],
                        default="standard",
                        max_length=20,
                        verbose_name="Тип на залата",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
            ],
            options={
                "verbose_name": "Учебна зала",
                "verbose_name_plural": "Учебни зали",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SchoolYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Учебна година"
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(default=False, verbose_name="Текуща"),
                ),
            ],
            options={
                "verbose_name": "Учебна година",
                "verbose_name_plural": "Учебни години",
                "ordering": ["-name"],
            },
        ),
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Наименование"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Пореден номер"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
            ],
            options={
                "verbose_name": "Смяна",
                "verbose_name_plural": "Смени",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Period",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveSmallIntegerField(verbose_name="Пореден час"),
                ),
                ("start_time", models.TimeField(verbose_name="Начален час")),
                ("end_time", models.TimeField(verbose_name="Краен час")),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="periods",
                        to="timetable.shift",
                        verbose_name="Смяна",
                    ),
                ),
            ],
            options={
                "verbose_name": "Учебен период",
                "verbose_name_plural": "Учебни периоди",
                "ordering": ["shift__order", "number"],
                "unique_together": {("shift", "number")},
            },
        ),
        migrations.CreateModel(
            name="TeacherAbsence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Начална дата")),
                ("end_date", models.DateField(verbose_name="Крайна дата")),
                (
                    "reason",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Причина"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Заявено"),
                            ("approved", "Потвърдено"),
                            ("rejected", "Отказано"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Регистрирано на"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registered_teacher_absences",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Регистрирано от",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        limit_choices_to={"role": "teacher"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_absences",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Преподавател",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отсъствие на преподавател",
                "verbose_name_plural": "Отсъствия на преподаватели",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="TimetableLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("lesson_create", "Създаване на час"),
                            ("lesson_update", "Промяна на час"),
                            ("lesson_delete", "Изтриване на час"),
                            ("publish", "Публикуване на разписание"),
                            ("substitution", "Назначаване или промяна на заместник"),
                            ("absence", "Отсъствие на преподавател"),
                            ("settings", "Промяна на настройки"),
                        ],
                        max_length=20,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Описание"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата и час"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="timetable_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Потребител",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запис в дневника",
                "verbose_name_plural": "Дневник на разписанието",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TimetableVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Чернова"),
                            ("published", "Публикувано"),
                            ("archived", "Архивирано"),
                        ],
                        default="draft",
                        max_length=10,
                        verbose_name="Състояние",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Създадено на"
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Публикувано на"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_timetables",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Създадено от",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="published_timetables",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Публикувано от",
                    ),
                ),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_versions",
                        to="school.class",
                        verbose_name="Клас",
                    ),
                ),
                (
                    "school_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="timetable.schoolyear",
                        verbose_name="Учебна година",
                    ),
                ),
            ],
            options={
                "verbose_name": "Версия на разписанието",
                "verbose_name_plural": "Версии на разписанието",
                "ordering": ["school_class__name", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Понеделник"),
                            (2, "Вторник"),
                            (3, "Сряда"),
                            (4, "Четвъртък"),
                            (5, "Петък"),
                        ],
                        verbose_name="Учебен ден",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lessons",
                        to="school.subject",
                        verbose_name="Предмет",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        limit_choices_to={"role": "teacher"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lessons",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Преподавател",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lessons",
                        to="timetable.period",
                        verbose_name="Пореден час",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lessons",
                        to="timetable.room",
                        verbose_name="Учебна зала",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="timetable.timetableversion",
                        verbose_name="Версия",
                    ),
                ),
            ],
            options={
                "verbose_name": "Час от разписанието",
                "verbose_name_plural": "Часове от разписанието",
                "ordering": ["day_of_week", "period__number"],
            },
        ),
        migrations.CreateModel(
            name="LessonTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата")),
                (
                    "topic",
                    models.CharField(max_length=255, verbose_name="Тема на урока"),
                ),
                ("note", models.TextField(blank=True, verbose_name="Забележка")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Въведена на"),
                ),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_topics",
                        to="school.class",
                        verbose_name="Клас",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lesson_topics",
                        to="school.subject",
                        verbose_name="Предмет",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        limit_choices_to={"role": "teacher"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lesson_topics",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Преподавател",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lesson_topics",
                        to="timetable.period",
                        verbose_name="Пореден час",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тема на урок",
                "verbose_name_plural": "Теми на уроци",
                "ordering": ["-date", "period__number"],
                "unique_together": {("date", "school_class", "period")},
            },
        ),
        migrations.CreateModel(
            name="CurriculumEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hours_per_week",
                    models.PositiveSmallIntegerField(verbose_name="Часове седмично"),
                ),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curriculum",
                        to="school.class",
                        verbose_name="Клас",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="curriculum",
                        to="school.subject",
                        verbose_name="Предмет",
                    ),
                ),
                (
                    "school_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curriculum",
                        to="timetable.schoolyear",
                        verbose_name="Учебна година",
                    ),
                ),
            ],
            options={
                "verbose_name": "Хорариум",
                "verbose_name_plural": "Седмичен хорариум",
                "ordering": ["school_class__name", "subject__name"],
                "unique_together": {("school_year", "school_class", "subject")},
            },
        ),
        migrations.CreateModel(
            name="ClassYearSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_language",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="first_language_classes",
                        to="school.subject",
                        verbose_name="Първи чужд език",
                    ),
                ),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="year_settings",
                        to="school.class",
                        verbose_name="Клас",
                    ),
                ),
                (
                    "second_language",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="second_language_classes",
                        to="school.subject",
                        verbose_name="Втори чужд език",
                    ),
                ),
                (
                    "school_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_settings",
                        to="timetable.schoolyear",
                        verbose_name="Учебна година",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="class_settings",
                        to="timetable.shift",
                        verbose_name="Смяна",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройка на клас",
                "verbose_name_plural": "Настройки на класове",
                "ordering": ["school_class__name"],
                "unique_together": {("school_year", "school_class")},
            },
        ),
        migrations.CreateModel(
            name="Substitution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата")),
                (
                    "is_cancelled",
                    models.BooleanField(default=False, verbose_name="Отменен час"),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Забележка"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Създадено на"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_substitutions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Създадено от",
                    ),
                ),
                (
                    "original_teacher",
                    models.ForeignKey(
                        limit_choices_to={"role": "teacher"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="substituted_lessons",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Основен преподавател",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="substitutions",
                        to="timetable.period",
                        verbose_name="Пореден час",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="substitutions",
                        to="timetable.room",
                        verbose_name="Учебна зала",
                    ),
                ),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="substitutions",
                        to="school.class",
                        verbose_name="Клас",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="substitutions",
                        to="school.subject",
                        verbose_name="Предмет",
                    ),
                ),
                (
                    "substitute_teacher",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "teacher"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="substitutions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Заместник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заместване",
                "verbose_name_plural": "Замествания",
                "ordering": ["-date", "period__number"],
                "unique_together": {("date", "school_class", "period")},
            },
        ),
        migrations.AddConstraint(
            model_name="timetableversion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "draft")),
                fields=("school_year", "school_class"),
                name="unique_draft_per_class",
            ),
        ),
        migrations.AddConstraint(
            model_name="timetableversion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "published")),
                fields=("school_year", "school_class"),
                name="unique_published_per_class",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="lesson", unique_together={("version", "day_of_week", "period")},
        ),
    ]
